export const CONTEST_ACTIONS = {
  SET_CONTEST: 'SET_CONTEST',
  UPDATE_CONTEST: 'UPDATE_CONTEST',
  CLEAR: 'CLEAR',
};

export const DOG_ACTIONS = {
  GET_DATA: 'GET_DATA',
  UPDATE_ONE_FIELD: 'UPDATE_ONE_FIELD',
  UPDATE_MANY_FIELDS: 'UPDATE_MANY_FIELDS',
  SET_DATA: 'SET_DATA',
  CLEAR_CHOSEN_DOG: 'CLEAR_CHOSEN_DOG',
};

export const USER_ACTIONS = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  UPDATE_FIELD: 'UPDATE_FIELD',
  CHANGE_USER: 'CHANGE_USER',
  SELECT_ROLE: 'SELECT_ROLE',
  CLEAR_SELECTED_ROLE: 'CLEAR_SELECTED_ROLE',
};
